Repository operate-first/curator-operator, pull requests merged in 2022-03, with the labels that each got.

#10 Add an OWNERS file
  OWNERS
Labels: size/XS

#8 Correct package imports
  PROJECT
  controllers/report_controller.go
  controllers/suite_test.go
  go.mod
  main.go
Labels: size/S, lgtm, approved

#11 Update any references to 'tflannag' -> 'operator-first'
  Makefile
  bundle/manifests/curator-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: size/XS

#12 bundle/metadata: Remove the unused properties.yaml file
  bundle/metadata/properties.yaml
Labels: size/S

#16 .github,Makefile: Consolidate verification checks into a Makefile target
  .github/workflows/ci.yaml
  Makefile
Labels: size/S

#25 controllers: Fix panic when accessing an invalid log statement
  controllers/fetchdata_controller.go
Labels: size/XS
