Repository operate-first/curator-operator, pull requests merged in 2022-07, with the labels that each got.

#48 Updated report controller
  api/v1alpha1/report_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/curator-operator.clusterserviceversion.yaml
  bundle/manifests/curator.operatefirst.io_reports.yaml
  config/crd/bases/curator.operatefirst.io_reports.yaml
  config/crd/bases/curator.operatorfirst.io_reports.yaml
  config/samples/curator_v1alpha1_report.yaml
  controllers/report_controller.go
  go.mod
  go.sum
  internal/db/postgres_interface.go
  internal/reporting/reporting.go
  main.go
Labels: lgtm, approved, size/XXL

#63 Generate report for daily, weekly, monthly using API
  PROJECT
  api/v1alpha1/reportapi_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/curator-operator.clusterserviceversion.yaml
  bundle/manifests/curator.operatefirst.io_reportapis.yaml
  config/crd/bases/curator.operatefirst.io_reportapis.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_reportapis.yaml
  config/crd/patches/webhook_in_reportapis.yaml
  config/manifests/bases/curator-operator.clusterserviceversion.yaml
  config/rbac/reportapi_editor_role.yaml
  config/rbac/reportapi_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/curator_v1alpha1_reportapi.yaml
  config/samples/kustomization.yaml
  controllers/reportapi_controller.go
  internal/http.go
  main.go
Labels: size/XL, lgtm, approved

#64 S3 feature-integration
  api/v1alpha1/fetchdata_types.go
  config/crd/bases/curator.operatefirst.io_fetchdata.yaml
  config/samples/curator_v1alpha1_fetchdata.yaml
  controllers/fetchdata_controller.go
Labels: lgtm, approved, size/M

#66 Automatically update DB tables and routines without manual deployment
  .gitignore
  internal/db/psqldb.go
  main.go
Labels: size/L, lgtm, approved

#67 Added auto email feature for sending emails for daily, weekly and monthly reports
  .gitignore
  api/v1alpha1/report_types.go
  config/crd/bases/curator.operatefirst.io_reports.yaml
  config/samples/curator_v1alpha1_report.yaml
  controllers/report_controller.go
  internal/db/psqldb.go
  main.go
Labels: size/L, lgtm, approved

#68 Added configuration files
  Documentation/config/db-secret-file.yaml
  Documentation/config/kokumetric-report.yaml
  Documentation/config/kokumetris-cfg.yaml
  Documentation/config/postgres-database-cfg.yaml
Labels: size/L, lgtm, approved
