Repository operate-first/curator-operator, pull requests merged in 2022-08, with the labels that each got.

#71 Add description for how to encode creds
  Documentation/config/db-secret-file.yaml
Labels: size/XS, lgtm, approved

#73 Added config files
  Documentation/config/db-secret-file.yaml
  Documentation/config/kokumetric-report.yaml
  Documentation/config/kokumetris-cfg.yaml
  Documentation/config/postgres-database-cfg.yaml
Labels: size/L, lgtm, approved

#72 Added config files
  Documentation/config/db-secret-file.yaml
  Documentation/config/kokumetric-report.yaml
  Documentation/config/kokumetris-cfg.yaml
  Documentation/config/postgres-database-cfg.yaml
Labels: size/L, lgtm, approved

#74 Added new PSQL DB monitor scripts and the container internals
  Documentation/config/postgres-database-monitor.yaml
  internal/psql_db_internals/Dockerfile
  internal/psql_db_internals/curator-modified-psql/Dockerfile
  internal/psql_db_internals/curator-modified-psql/docker-entrypoint.sh
  internal/psql_db_internals/email_alert.py
  internal/psql_db_internals/execute_py.sh
Labels: size/XL, lgtm, approved

#76 update metrics list
  api/v1alpha1/reportapi_types.go
Labels: size/XS, lgtm, approved

#75 added feature - database cleanup
  api/v1alpha1/fetchdata_types.go
  config/crd/bases/curator.operatefirst.io_fetchdata.yaml
  config/samples/curator_v1alpha1_fetchdata.yaml
  controllers/fetchdata_controller.go
Labels: size/L, lgtm, approved
