Repository operate-first/curator-operator, pull requests merged in 2022-04, with the labels that each got.

#28 .github: Bump the golangci-lint action in the CI workflow
  .github/workflows/ci.yaml
Labels: size/XS

#29 Dockerfile: Ensure the internal/ directory is copied
  Dockerfile
Labels: size/XS

#30 ci: Add check for building the controller's container image
  .github/workflows/ci.yaml
Labels: size/S

#31 config,controllers: Fix kubebuilder RBAC generation markers for the fetchdata-operator
  bundle/manifests/curator-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/fetchdata_controller.go
Labels: size/M

#32 Added PostgreSQL library
  go.mod
  go.sum
  main.go
Labels: size/XS, lgtm, approved

#34 Makefile: Remove the unused postgres target
  Makefile
Labels: size/XS

#36 Sample yaml for FetchData and Reports
  bundle/manifests/curator-operator.clusterserviceversion.yaml
  config/samples/curator_v1alpha1_fetchdata.yaml
  config/samples/curator_v1alpha1_report.yaml
Labels: lgtm, approved, size/M, do-not-merge/hold

#37 update postgres dependancy from lib/pq to pgx
  controllers/report_controller.go
  go.mod
  go.sum
  main.go
Labels: size/L, lgtm, approved

#9 Generate report as .CSV file
  Makefile
  cmd/server/main.go
  go.mod
  go.sum
  internal/http.go
  internal/signals/signals.go
Labels: size/L, lgtm, approved

#38 Logging issue in report controller
  controllers/report_controller.go
Labels: size/XS, lgtm, approved
